package com.codewithprojects.springsecurity.controller;

import com.codewithprojects.springsecurity.dto.PaymentRequest;
import com.codewithprojects.springsecurity.dto.PaymentResponse;
import com.codewithprojects.springsecurity.services.PaymentService;
import com.codewithprojects.springsecurity.services.PaymentServiceFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

// Code Generated by Sidekick is for learning and experimentation purposes only.
@RestController
@RequestMapping("/api/payments")
public class PaymentController {
    @Autowired
    private PaymentServiceFactory paymentServiceFactory;

    @PostMapping("/pay")
    public ResponseEntity<PaymentResponse> pay(@RequestBody PaymentRequest request) {
        PaymentService service = paymentServiceFactory.getService(request.getMethod());
        PaymentResponse response = service.processPayment(request);
        return ResponseEntity.ok(response);
    }
}
