// Code Generated by Sidekick is for learning and experimentation purposes only.
package com.codewithprojects.springsecurity.controller;

import com.codewithprojects.springsecurity.dto.TurfRequestDto;
import com.codewithprojects.springsecurity.dto.TurfResponseDto;
import com.codewithprojects.springsecurity.services.TurfService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/v1/turfs")
@RequiredArgsConstructor
public class TurfController {

    private final TurfService turfService;

    @PreAuthorize("hasRole('OWNER')")
    @PostMapping
    public ResponseEntity<TurfResponseDto> addTurf(@RequestBody TurfRequestDto turfRequestDto, Authentication authentication) {
        String username = authentication.getName();
        TurfResponseDto responseDTO = turfService.createTurfForOwner(turfRequestDto, username);
        return ResponseEntity.ok(responseDTO);
    }
}

