// Code Generated by Sidekick is for learning and experimentation purposes only.
package com.codewithprojects.springsecurity.dto;

import com.codewithprojects.springsecurity.entities.Role;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

@Data
public class SignUpRequest {

    @NotBlank(message = "First name is required")
    private String firstName;

    @NotBlank(message = "Last name is required")
    private String lastName;

    @NotBlank(message = "Email is required")
    @Email(message = "Email should be valid")
    private String email;

    @NotBlank(message = "Password is required")
    private String password;

    @NotNull(message = "Role is required")
    private Role role;
}
























//package com.codewithprojects.springsecurity.dto;
//
//import com.codewithprojects.springsecurity.entities.Role;
//import lombok.Data;
//
//@Data
//public class SignUpRequest {
//
//    private String firstName;
//    private String lastName;
//    private String email;
//    private String password;
//    private Role role;
//}
